module.exports = {
  apps: [
    {
      name: "trading-website",
      script: "npm",
      args: "start",
      cwd: "/home/deploy/trading-website",
      instances: 2,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      max_memory_restart: "1G",
      error_file: "/home/deploy/logs/website-error.log",
      out_file: "/home/deploy/logs/website-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: "10s",
    },
    {
      name: "discord-bot",
      script: "npm",
      args: "run bot",
      cwd: "/home/deploy/trading-website",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "500M",
      error_file: "/home/deploy/logs/bot-error.log",
      out_file: "/home/deploy/logs/bot-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      autorestart: true,
      watch: false,
      max_restarts: 10,
      min_uptime: "10s",
    },
  ],
}
